name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14]

    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v1
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: |
          curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
          yarn
      - name: yarn build
        run: |
          yarn fmt
          yarn lint
